version: '3'
services:
  db:
    image: mysql
    expose:
      - "3306"
    volumes:
      - /opt/storage/mysql:/var/lib/mysql
  repo:
    image: gogs/gogs
    expose:
      - "6022"
      - "3000"
    ports:
      - 6022:6022
    volumes:
      - /opt/storage/gogs:/data
  home:
    image: craft-flask:master
    volumes:
      - /opt/storage/craft-home/:/opt/app
    expose:
      - "8888"
    command: [python, ./app.py]
  api: 
    image: craft-flask:master
    volumes:
      - /opt/storage/craft-api/:/opt/app
    expose:
      - "8888"
    command: [python, ./app.py]  
  proxy:
    image: nginx:latest
    volumes:
      - /opt/storage/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /opt/storage/nginx/pki/:/etc/nginx/pki/
    ports:
      - 80:80
      - 443:443
  vault:
    image: craft-vault:master
    volumes:
      - /opt/storage/vault/config:/vault/config
      - /opt/storage/vault/pki:/vault/pki
      - /opt/storage/vault/log:/vault/logs
      - /opt/storage/vault/data:/vault/data
    expose:
      - "8200"
    entrypoint: vault server -config /vault/config/config.hcl
    privileged: true